home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', homePage, name="homepage"),
    path('register/', registerPage, name='register'),
    path('login/', loginPage, name='login'),
    path('logout/', logoutPage, name='logout'),
    path('live/', livePage, name='live'),
    path('news/', news, name='news'),
    path('savecomment/', saveComment, name="saveComment"),
    path('getComment/', getComment, name="getComment"),
    path('video/',video, name='video')

]

accounts/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User

class Country(models.Model):
    name = models.CharField(max_length=100, unique=True)
    code = models.CharField(max_length=50, unique=True)
    image = models.ImageField(upload_to='photos/country', blank=True)
    status = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'countries'
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    status = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'categories'
        verbose_name = 'Category'
        verbose_name_plural = 'Category'

    def __str__(self):
        return self.name

class Game(models.Model):
    STATUS = (
        ('ready-to-start', 'Ready to Start'),
        ('ongoing', 'Ongoing'),
        ('end', 'End')
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    team1 = models.ForeignKey(Country, null=True, related_name='rel_category', on_delete=models.SET_NULL)
    team2 = models.ForeignKey(Country, null=True, related_name='rel_category_id', on_delete=models.SET_NULL)
    status = models.CharField(max_length=100, choices=STATUS)
    point1 = models.CharField(max_length=10, blank=True, null=True)
    point2 = models.CharField(max_length=10, blank=True, null=True)
    liveLink = models.CharField(max_length=150, blank=True, null=True)
    videoTitle = models.CharField(max_length=150, blank=True, null=True)
    video=models.FileField(upload_to="video/%y", blank=True, null=True)
    startTime = models.DateTimeField(blank=True, null=True)
    class Meta:
        db_table = 'games'
        verbose_name = 'Game'
        verbose_name_plural = 'Games'

    def __str__(self): 
        return self.team1.name + " VS " + self.team2.name


class Comment(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()

    class Meta:
        db_table = 'comments'
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return str(self.game)



    

templates/backend/category/category.html
{% extends 'backend/base.html' %}

{% block content %}

  <!-- Page -->
  <div class="page">
    <div class="page-header">
      <h1 class="page-title">Category</h1>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        {% comment %} <li class="breadcrumb-item"><a href="javascript:void(0)">Tables</a></li> {% endcomment %}
        <li class="breadcrumb-item active">Category</li>
      </ol>
      <div class="page-header-actions">
        <a class="btn btn-success" href="{% url 'create-category' %}">Create</a>
        {% comment %} <a class="btn btn-sm btn-default btn-outline btn-round" href="http://datatables.net"
          target="_blank">
            <i class="icon wb-link" aria-hidden="true"></i>
            <span class="hidden-sm-down">Official Website</span>
        </a> {% endcomment %}
      </div>
    </div>

    <div class="page-content">
    <!-- Panel Table Tools -->
    <div class="panel">
        <header class="panel-heading">
        <h3 class="panel-title">Category List</h3>
        </header>
        <div class="panel-body">
        <table class="table table-hover dataTable table-striped w-full" id="exampleTableTools">
            <thead>
            <tr>
                <th>SN</th>
                <th>Category Name</th>
                <th>Date Created</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
              <th>SN</th>
              <th>Category Name</th>
              <th>Date Created</th>
              <th>Actions</th>
            </tr>
            </tfoot>
            <tbody>
              {% for category in categories %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ category.name }}</td>
                  <td>{{ category.date_created }}</td>
                  <td>
                    <a href="{% url 'update-category' category.id %}">
                      <i class="icon fa-edit" aria-hidden="true"></i>
                    </a>
                    <a href="{% url 'delete-category' category.id %}">
                      <i style="padding-left:10px;" class="icon fa-trash" aria-hidden="true"></i>
                    <a>
                  </td>
                </tr> 
              {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
    <!-- End Panel Table Tools -->
  </div>

{% endblock content %}

templates/backend/category/createCategory.html
{% extends 'backend/base.html' %}

{% block content %}
     <!-- Page -->
     <div class="page">
        <div class="page-header">
          <h1 class="page-title">Create Category</h1>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'get-category' %}">Category</a></li>
            <li class="breadcrumb-item active">Create</li>
          </ol>
        </div>
  
        <div class="page-content">
          <!-- Panel Form Elements -->
          <div class="panel">
            <div class="panel-heading">
              <h3 class="panel-title">Catefory Form</h3>
            </div>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="panel-body container-fluid">
                    <div class="row row-lg">
                        <div class="col-md-6 col-lg-4">
                            <!-- Example Input Focus -->
                            <div class="example-wrap">
                                <h4 class="example-title">Country Name</h4>
                                {{ form.name }}
                            </div>
                            <!-- End Example Input Focus -->
                        </div>

                        <div class="col-md-6 col-lg-4">
                            <!-- Example Input Focus -->
                            <div class="example-wrap">
                                <h4 class="example-title">Status</h4>
                                {{ form.status }}
                            </div>
                            <!-- End Example Input Focus -->
                        </div>
                    </div>
                </div>
                <div class="col-md">
                    <button type="submit" class="btn btn-sm btn-success">Submit</button>
                    <a class="btn btn-sm btn-danger" href="{% url 'get-country' %}">Cancel</a>
                </div>
            </form>
          </div>
          <!-- End Panel Form Elements -->
        </div>
      </div>
      <!-- End Page -->
{% endblock %}


{% block customJavascript %}
      <script>
        $(document).ready(function(){
            $('input[type="file"]').change(function(e) {
                var file = e.target.files[0].name;
                $('#image_name').val(file)
            });
        })

        $(document).ready(function(){
            $('#id_status').removeClass('form-control focus')
        })
      </script>

{% endblock customJavascript %}